version: 2
jobs:
  build:
    working_directory: ~/circleci-java-sbhw

    environment:
      MAVEN_OPTS: -Xmx3200m

    docker:
      - image: circleci/openjdk:8-jdk-stretch

    steps:

      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-

      - run: mvn clean package # run the actual tests

      - save_cache: # saves the project dependencies
          paths:
            - ~/.m2
          key: v2-dependencies-{{ checksum "pom.xml" }}

      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/surefire/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/surefire/ \;
          when: always

      - store_test_results:
          path: ~/test-results

      - store_artifacts:
          path: ~/test-results/surefire
  
  demo-deploy:
    docker:
    - image: zenikalabs/rancher-cli
    
    working_directory: ~/circleci-java-sbhw
    
    steps:
      - attach_workspace:
          at: ~/circleci-java-sbhw

      - run:
        name: Echo hello world
        command: |
          echo "Hello World after manual approval"


workflows:
  version: 2 
  
  my_workflow:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
          filters:
            branches:
              only: master
      - demo-deploy:
          requires:
            - hold # manual approval required via the CircleCI UI to run the live-deploy job
          filters:
            branches:
              only: master
